name: Frontend Deployment Pipeline (Production)

on:
  push:
    branches:
         - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Notify Build Started
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="🚀 *Build Started*
          
          📦 Repo: ${{ github.repository }}
          🌿 Branch: ${{ github.ref_name }}
          👤 Actor: ${{ github.actor }}"

          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "content": "🚀 **Build Started**\n\n📦 Repo: ${{ github.repository }}\n🌿 Branch: ${{ github.ref_name }}\n👤 Actor: ${{ github.actor }}"
          }'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build
        env:
          VITE_JAVA_API_URL: ${{ secrets.VITE_JAVA_API_URL }}
          VITE_PYTHON_API_URL: ${{ secrets.VITE_PYTHON_API_URL }}

      - name: ❌ Notify Build Failed
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="❌ *Build Failed*
          
          📦 Repo: ${{ github.repository }}
          🌿 Branch: ${{ github.ref_name }}
          🔗 Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"

          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "content": "❌ **Build Failed**\n\n📦 Repo: ${{ github.repository }}\n🌿 Branch: ${{ github.ref_name }}\n🔗 Commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          }'

      - name: ✅ Notify Build Success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="✅ *Build Successful*
          
          📦 Repo: ${{ github.repository }}
          🌿 Branch: ${{ github.ref_name }}"

          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "content": "✅ **Build Successful**\n\n📦 Repo: ${{ github.repository }}\n🌿 Branch: ${{ github.ref_name }}"
          }'

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Notify Deploy Started
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="🚀 *Deployment Started*"

          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "content": "🚀 **Deployment Started**"
          }'

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME_PROD }}/ \
            --delete \
            --region us-east-1

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_PROD }} \
            --paths "/*"

      - name: ❌ Notify Deploy Failed
        if: failure()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="❌ *Deployment Failed*"

          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "content": "❌ **Deployment Failed**"
          }'

      - name: ✅ Notify Deploy Success
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d parse_mode=Markdown \
          -d text="✅ *Deployment Successful*
          
          🌍 Environment: PRODUCTION"

          curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "content": "✅ **Deployment Successful**\n\n🌍 Environment: PRODUCTION - https://d3mhewjhj8eneu.cloudfront.net"
          }'